apiVersion: v1
kind: Pod
metadata:
  name: jenkins-lts-jenkins-agent-static
  namespace: jenkins
  labels:
    app: jenkins-agent
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent
    securityContext:
      runAsUser: 0  # root 권한으로 실행
    command: ["/bin/sh", "-c"]
    args:
      - apt-get update && apt-get install -y docker.io &&
        curl -sO http://jenkins-lts:8080/jnlpJars/agent.jar &&
        java -jar agent.jar -url http://jenkins-lts:8080/ -secret "$(JNLP_SECRET)" -name "jenkins-lts-jenkins-agent-static" -webSocket -workDir "/home/jenkins/agent"
    env:
    - name: JNLP_SECRET
      valueFrom:
        secretKeyRef:
          name: jenkins-agent-secret
          key: JNLP_SECRET
    - name: DOCKER_HOST
      value: "unix:///var/run/docker.sock"  # Docker 연결
    volumeMounts:
    - name: workdir
      mountPath: /home/jenkins/agent
    - name: docker-sock
      mountPath: /var/run/docker.sock  # Docker 소켓 마운트
  volumes:
  - name: workdir
    emptyDir: {}
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket  # Docker 소켓 공유
  nodeSelector:
    topology.kubernetes.io/zone: "AZ2"
  tolerations:
    - key: "jenkins-agent"
      operator: "Exists"
  restartPolicy: Always
