apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-lts-pv
spec:
  capacity:
    storage: 50Gi  # 원하는 용량 설정
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # PV 삭제 시 데이터를 유지
  hostPath:
    path: /data/jenkins-lts  # Kubernetes 노드의 실제 경로

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-2.401-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # PV의 용량과 일치하게 설정
  volumeName: jenkins-lts-pv  # 위에서 정의한 PV 이름
  storageClassName: ""



--- nfs 방식 ---
  apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs-pv
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.19.204.11
    path: /fstfs0sfqcki01_sscoff

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: jenkins-nfs-pv
  storageClassName: ""

